### PR TITLE
CircleCI Orb Upgrade

### PR DESCRIPTION
**Pull request by xorima**
Use v2 orb

Signed-off-by: Jason Field <jason@avon-lea.co.uk>

## Description

[Describe what this change achieves]

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
Yay, terraform org update!

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by xorima** [comment]
Failing due to snort cookbook, will leave open and move on,

I think we should combine this into the snort cookbook, this is 100% a snort thing 
`Chef cookbook for installing the Snort ruleset update utility Pulled Pork`

Any issues @damacus

**Comment by damacus** [comment]
I think we need to update a bunch of versions

https://www.snort.org/downloads you'll find all the OpenSource version on this page. 

By the looks of things they've stopped supporting Centos6 (maybe).

**Comment by xorima** [comment]
Hi @damacus 

The reason for the failures are due to the snort cookbook failing, that's why this is something we should tackle to bring into a single cookbook, the dependancies are too coupled imo for them not to be the same cookbook

**Comment by damacus** [comment]
Agreed, maybe we should deprecate this.

**Pull request closed without merging**
